"""comment table

Revision ID: 1413dcc075ce
Revises: 6f3e7db41dcb
Create Date: 2021-01-06 16:03:35.919077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1413dcc075ce'
down_revision = '6f3e7db41dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chef_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer()),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chef_id'], ['chefs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
